---
- hosts: local
  tasks:
   - name: Ensure group "dmmgr" exists
     group:
       name: dmmgr
       state: present
   - name: create an user DSPDINFIICS
     user:
       name: DSPINFIICS
       comment: root user
       uid: 10000
       groups:
         - wheel
         - dmmgr