- name: create a ec2 instance
  hosts: local
  connection: local
  tasks:
    - name: Launch instance
      ec2:
        key_name: <your key name>
        instance_type: t2.micro
        image: ami-xxxxxxx
        instance_tags:
          Name: testing_ansible_EC2
        wait: yes
        group: <security group name>
        count: 1
        vpc_subnet_id: subnet-xxxxxxx
        assign_public_ip: yes
        region: us-east-1
      register: ec2

    - name: Add new instance to host group
      add_host: hostname={{ item.private_ip }} groupname=launched
      with_items: '{{ec2.instances}}'
	
    - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
      local_action: lineinfile 
                    dest="/etc/ansible/hosts" 
                    regexp={{ item.private_ip }} 
                    insertafter="[webserver]" line={{ item.private_ip }}
      with_items: '{{ec2.instances}}'

    - meta : refresh_inventory

    - name: Wait for server to restart
      local_action: wait_for
                    host={{ inventory_hostname }}
                    port=22
                    delay=240
                    timeout=300

- name: copy files in the new machines
  hosts: webserver
  remote_user: ubuntu
  become_method: sudo
  become: true
  tasks:
    - name: See if it is there
      debug: var=group_names
    - name: copy files to the new macine
      copy: src=/etc/ansible/launchEc2/demo.txt dest=/home/ubuntu/demo.txt mode=0644
