- name: create a ec2 instance
  hosts: local
  connection: local
  tasks:
    - name: Launch instance
      ec2:
        key_name: <key_pair_name>
        instance_type: t2.micro
        image: ami-xxxxxxxx
        instance_tags:
          Name: testing_ansible
        wait: yes
        group: <security_group_name>
        count: 1
        vpc_subnet_id: subnet-xxxxxxxx
        assign_public_ip: yes
        region: us-east-1
      register: ec2
    - name: Add new instance to host group
      add_host: hostname={{ item.private_ip }} groupname=launched
      with_items: '{{ec2.instances}}'
    - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
      local_action: lineinfile
                    dest="/etc/ansible/hosts"
                    regexp={{ item.private_ip }}
                    insertafter="[webserver]" line={{ item.private_ip }}
      with_items: ec2.instances
#- name: copy files in the new maachines
#  hosts: webserver

#  become: sudo
#  tasks:
#    - name: See if it is there
#      debug: var=group_names

#    - name: copy files to the new macine
#      copy: src=/etc/ansible/launchEc2/demo.txt dest=/home/ec2-user/demo.txt mode=0644
